language: java,c
jdk:
  - oraclejdk8

branches:
  only:
  - eval-travis-ci

dist: trusty

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake libunittest++-dev libboost-all-dev libprotobuf-dev protobuf-compiler

before_script:
  - git clone https://github.com/efficient/libcuckoo.git
  - pushd libcuckoo && git checkout v0.2 && cmake . && sudo make install && popd
  - git clone https://github.com/janmejay/medida.git
  - pushd medida && cmake CMakeLists.txt && sudo make install && popd
  - git clone https://github.com/google/cityhash.git
  - pushd cityhash && git checkout 8af9b8c2b889d80c22d6bc26ba0df1afb79a30db && ./configure && make all check CXXFLAGS="-g -O3" && sudo make install && sudo ldconfig && popd
script:
  - pushd recorder && cmake CMakeLists.txt && make && popd
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
