language: java
jdk:
  - oraclejdk8
# safelist
branches:
  only:
  - eval-travis-ci

install: true
before_script:
  - git clone https://github.com/efficient/libcuckoo.git
  - pushd libcuckoo && cmake install && make install && popd
script:
  - pushd recorder && cmake CMakeLists.txt && make && popd
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
