language: java
jdk:
  - oraclejdk8
# safelist
branches:
  only:
  - eval-travis-ci

dist: trusty

env:
  global:
    export PROTOBUF_BASE_DIR=/opt/protobuf
    export PROTOBUF_LIB_DIR=/opt/protobuf/lib

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake libunittest++-dev libboost-all-dev protobuf-compiler

before_script:
  - protoc --version
  - apt-cache policy libprotobuf-dev
  - git clone https://github.com/efficient/libcuckoo.git
  - pushd libcuckoo && cmake . && sudo make install && popd
  - git clone https://github.com/janmejay/medida.git
  - pushd medida && cmake CMakeLists.txt && sudo make install && popd
  - git clone https://github.com/google/cityhash.git
  - pushd cityhash && ./configure && make all check CXXFLAGS="-g -O3" && sudo make install && popd
script:
  - pushd recorder && cmake CMakeLists.txt && make && popd
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
