language: java
jdk:
  - oraclejdk8
# safelist
branches:
  only:
  - eval-travis-ci

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-4.9
      - g++-4.9
      - libunittest++-dev
      - libprotobuf-dev
      - boost-all

env:
  global:
    - CXX=g++-4.9
    - CC=gcc-4.9

install: true

before_script:
  - git clone https://github.com/efficient/libcuckoo.git
  - pushd libcuckoo && cmake . && sudo make install && popd
  - git clone https://github.com/janmejay/medida.git
  - pushd medida && cmake CMakeLists.txt && sudo make install && popd
script:
  - pushd recorder && cmake CMakeLists.txt && make && popd
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
